#!/usr/bin/env python3
#
#  gen_mp2.py --- the integer parts of mp2.hpp, from third_party/pl_mpeg.h.
#
#  Usage: tools/gen_mp2.py third_party/pl_mpeg.h mp2_synth.inc
#
#  pl_mpeg's MP2 decoder (after kjmp2 by Martin J. Fiedler) works in integers
#  up to the synthesis filterbank, which it does in float.  This writes that
#  part as integers, for a player that may not touch a floating-point
#  register (see README.md):
#
#    - the 512-tap synthesis window, whose values are all multiples of 0.5,
#      doubled: exact as int32_t (they reach about +-37000);
#    - the 32-point DCT, each `(expr) * c` turned into M(expr, c in Q15): a
#      64-bit product shifted back down.  The samples it gets are about
#      +-2^17, the largest constant is about 10.2, so nothing overflows.
#
import re
import sys

src = open(sys.argv[1]).read()

m = re.search(r"static const float PLM_AUDIO_SYNTHESIS_WINDOW\[\] = \{(.*?)\};", src, re.S)
if not m:
    sys.exit("gen_mp2: no synthesis window in " + sys.argv[1])
values = [float(v) for v in re.findall(r"-?\d+\.\d+", m.group(1))]
if len(values) != 512:
    sys.exit("gen_mp2: the window has %d values, not 512" % len(values))
window = []
for v in values:
    d = v * 2
    if d != int(d):
        sys.exit("gen_mp2: %r is not a multiple of 0.5" % v)
    window.append(int(d))

m = re.search(r"void plm_audio_idct36\(int s\[32\]\[3\], int ss, float \*d, int dp\) \{(.*?)\n\}", src, re.S)
if not m:
    sys.exit("gen_mp2: no plm_audio_idct36 in " + sys.argv[1])
body = m.group(1)
body = body.replace("float t01", "int32_t t01")
body = body.replace("(float)", "")
body = body.replace("0.0;", "0;")

def q15(mo):
    expr, c = mo.group(1), float(mo.group(2))
    return "M(%s, %d)" % (expr, round(c * 32768))

body, n = re.subn(r"\(([^()]+)\) \* ([0-9]+\.[0-9]+)f", q15, body)
if n < 60 or "f;" in body or re.search(r"\d\.\d", body):
    sys.exit("gen_mp2: the DCT did not convert cleanly (%d products)" % n)

out = open(sys.argv[2], "w")
out.write("// Generated by tools/gen_mp2.py from third_party/pl_mpeg.h. Do not edit.\n\n")
out.write("// The synthesis window, doubled.\n")
out.write("static const int32_t MP2_WINDOW[512] = {\n")
for i in range(0, 512, 12):
    out.write("    " + ", ".join("%d" % v for v in window[i:i + 12]) + ",\n")
out.write("};\n\n")
out.write("// A 64-bit product with a Q15 constant, back to 32 bits.\n")
out.write("#define M(a, c) ((int32_t)(((int64_t)(a) * (c)) >> 15))\n\n")
out.write("static void mp2_idct36(int s[32][3], int ss, int32_t *d, int dp)\n{")
out.write(body)
out.write("\n}\n\n#undef M\n")
print("gen_mp2: window and %d products" % n)
