/*
 *  jsr2c --- compiles a script to QuickJS bytecode, as a C array.
 *
 *      jsr2c input.js output.c symbol
 *
 *  Runs on the host, with the same QuickJS sources the r2 build uses: the
 *  bytecode format and the atom table do not depend on the C library or on
 *  CONFIG_R2, so what this writes loads unchanged in the r2 engine
 *  (jsr2::Engine::evalBinary).  A syntax error stops the build with the
 *  file and line.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "quickjs.h"

int main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr, "usage: jsr2c input.js output.c symbol\n");
        return 2;
    }
    FILE *f = fopen(argv[1], "rb");
    if (!f) {
        perror(argv[1]);
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *src = malloc((size_t)len + 1);
    if (!src || fread(src, 1, (size_t)len, f) != (size_t)len) {
        fprintf(stderr, "%s: cannot read\n", argv[1]);
        return 1;
    }
    src[len] = 0;
    fclose(f);

    JSRuntime *rt = JS_NewRuntime();
    /* Function.prototype.toString() of prelude functions is not worth a copy
     * of the source in every image; line numbers stay for stack traces. */
    JS_SetStripInfo(rt, JS_STRIP_SOURCE);
    JSContext *ctx = JS_NewContext(rt);
    /* The name is what stack traces show: the file's base name. */
    const char *name = strrchr(argv[1], '/');
    name = name ? name + 1 : argv[1];
    JSValue fn = JS_Eval(ctx, src, (size_t)len, name, JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_COMPILE_ONLY);
    if (JS_IsException(fn)) {
        JSValue ex = JS_GetException(ctx);
        const char *msg = JS_ToCString(ctx, ex);
        JSValue stack = JS_GetPropertyStr(ctx, ex, "stack");
        const char *where = JS_IsString(stack) ? JS_ToCString(ctx, stack) : NULL;
        fprintf(stderr, "%s: %s\n%s", argv[1], msg ? msg : "error", where ? where : "");
        return 1;
    }
    size_t size;
    uint8_t *bc = JS_WriteObject(ctx, &size, fn, JS_WRITE_OBJ_BYTECODE);
    if (!bc) {
        fprintf(stderr, "%s: cannot write bytecode\n", argv[1]);
        return 1;
    }
    FILE *out = fopen(argv[2], "w");
    if (!out) {
        perror(argv[2]);
        return 1;
    }
    fprintf(out, "/* Generated by jsr2c from %s; do not edit. */\n#include <stddef.h>\n#include <stdint.h>\n", name);
    fprintf(out, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n");
    fprintf(out, "extern const uint8_t %s[];\nextern const size_t %s_size;\n", argv[3], argv[3]);
    fprintf(out, "const size_t %s_size = %zu;\n", argv[3], size);
    fprintf(out, "__attribute__((aligned(8))) const uint8_t %s[%zu] = {", argv[3], size);
    for (size_t i = 0; i < size; i++)
        fprintf(out, "%s%u,", i % 24 ? "" : "\n", bc[i]);
    fprintf(out, "\n};\n#ifdef __cplusplus\n}\n#endif\n");
    fclose(out);
    js_free(ctx, bc);
    JS_FreeValue(ctx, fn);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    free(src);
    return 0;
}
