#ifndef _THEM_INT_INCLUDED_
#define _THEM_INT_INCLUDED_ 

/*
 *  int.h
 *
 *  krusty@vxn.dev / Nov 4, 2025
 */

#include "cpu.h"

#ifdef __cplusplus
extern "C" {
#endif

enum SRV_21H
{
	PROGRAM_TERMINATE 		= 0x00,
	CHAR_INPUT_W_ECHO,
	CHAR_OUTPUT,
	AUX_INPUT,
	AUX_OUTPUT,
	PRINTER_OUTPUT,
	DIRECT_CONS_IO,
	UNFILTERED_CHAR_INPUT,
	CHAR_INPUT,
	CHAR_STRING_OUTPUT,
	BUFFERED_INPUT,
	GET_INPUT_STATUS,
	RESET_INPUT_BUFFER_AND_INPUT,
	DISK_RESET,
	SET_DEF_DISK_DRIVE,
	OPEN_FILE,
	CLOSE_FILE			= 0x10,
	FIND_FIRST_FILE,
	FIND_NEXT_FILE,
	DELETE_FILE,
	SEQUENTIAL_READ,
	SEQUENTIAL_WRITE,
	CREATE_OR_TRUNCATE_FILE,
	RENAME_FILE,
	RESERVED_18H,
	GET_DEF_DISK_DRIVE,
	SET_DISK_TRANSFER_AREA_ADDR,
	GET_CURRENT_DRIVE_ALLOC_DATA,
	GET_ALLOC_DATA_FOR_SPEC_DRIVE,
	RESERVED_1DH,
	RESERVED_1EH,
	RESERVED_1FH,
	RESERVED_20H			= 0x20,
	RANDOM_READ,
	RANDOM_WRITE,
	GET_FILE_SIZE_IN_RECORDS,
	SET_RANDOM_RECORD_NUM,
	SET_INTERRUPT_VECTOR,
	CREATE_PROGRAM_SEGMENT_PREFIX,
	RANDOM_BLOCK_READ,
	RANDOM_BLOCK_WRITE,
	PARSE_FILENAME,
	GET_SYSTEM_DATE,
	SET_SYSTEM_DATE,
	GET_SYSTEM_TIME,
	SET_SYSTEM_TIME,
	SET_VERIFY_FLAG,
	GET_DTA_ADDRESS,
	GET_DOS_VERSION			= 0x30,
	TERMINATE_AND_STAY_RESIDENT,
	GET_DISK_INFO,
	GET_SET_CTRL_BREAK_FLAG,
	FIND_ACTIVE_BYTE,
	GET_INTERRUPT_VECTOR,
	GET_FREE_DISK_SPACE,
	RESERVED_37H,
	GET_COUNTRY_INFORMATION,
	CREATE_SUBDIRECTORY,
	DELETE_SUBDIRECTORY,
	SET_CURRENT_DIRECTORY,
	CREATE_OR_TRUNCATE_FILE_3CH,
	OPEN_FILE_3DH,
	CLOSE_FILE_3EH,
	READ_FILE_OR_DEVICE,
	WRITE_FILE_OR_DEVICE		= 0x40,
	DELETE_FILE_41H,
	MOVE_FILE_POINTER,
	GET_OR_SET_FILE_ATTRS,
	DEVICE_DRIVER_CONTROL, /* IOCTL */
	DUPLICATE_HANDLE,
	FORCE_DUPLICATE_HANDLE,
	GET_CURRENT_DIRECTORY,
	ALLOC_MEMORY,
	RELEASE_MEMORY,
	RESERVED_4AH,
	EXECUTE_PROGRAM,
	TERMINATE_PROGRAM_WITH_RET_CODE,
	GET_RET_CODE,
	SEARCH_FOR_FIRST_MATCH,
	SEARCH_FOR_NEXT_MATCH,
	GET_DISK_INFO_50H		= 0x50,
	RESERVED_51H,
	RESERVED_52H,
	RESERVED_53H,
	GET_VERIFY_FLAG,
	RESERVED_55H,
	RENAME_FILE_56H,
	GET_SET_FILE_DATE_TIME,
	GET_SET_MEM_ALLOC_STRATEGY,
	GET_EXTENDED_ERROR_INFORMATION,
	CREATE_TEMP_FILE,
	CREATE_NEW_FILE,
	LOCK_UNLOCK_FILE_ACCESS,
	CRITICAL_ERROR_INFORMATION,
	NETWORK_SERVICES,
	NETOWRK_REDIRECTION,
	GET_FULLY_QUAL_FILE_NAME	= 0x60,
	RESERVED_61H,
	GET_ADDR_OF_PROG_SEGMENT_PREFIX,
	GET_SYS_LEAD_BYTE_TABLE,
	GET_DEVICE_DRIVER_LOOK_AHEAD,
	GET_EXTENDED_COUNTRY_INFO,
	GET_SET_GLOBAL_CODE_PAGE,
	SET_HANDLE_COUNT,
	FLUSH_BUFFER,
	GET_SET_DISK_SERIAL_NUMBER,
	RESERVED_6AH,
	RESERVED_6BH,
	EXTENDED_OPEN_CREATE,
};

void int21h(CPU_T *cpu, uint8_t *memory);

#ifdef __cplusplus
}
#endif

#endif
