NAME            ?= placeholder

BUILD_DIR	    ?= ./build

CRT0_OBJ	    ?= ${BUILD_DIR}/_crt0.o
PRG_OBJ		    ?= ${BUILD_DIR}/${NAME}.o
LIBCR2		    ?= ../libcr2

CRT0_ASM	    ?= ${LIBCR2}/_crt0.asm

SOURCE_FILES	?= ../*.c
OPT_LEVEL       ?= -O2
EXTRA_CFLAGS    ?=

export


.PHONY: build

ensure_build_dir:
	@mkdir -p ${BUILD_DIR}

build_crt0: ensure_build_dir
	@nasm -f elf64 ${CRT0_ASM} -o ${CRT0_OBJ}

compile: ensure_build_dir
	@cd ${BUILD_DIR} && gcc \
		-c \
		${OPT_LEVEL} \
		-flto \
		-m64 \
		-static \
		-nostdlib \
		-nostdinc \
		-mno-red-zone \
		-ffreestanding \
		${EXTRA_CFLAGS} \
		-I .. \
		-I ../../libcr2/ \
		${SOURCE_FILES}

link: compile build_crt0
	@gcc \
		${OPT_LEVEL} \
		-flto \
		-nostdinc \
		-nostdlib \
		-nostartfiles \
		${BUILD_DIR}/*.o \
		-L .. \
		-lcr2 \
		-static \
		-Xlinker "-T../linker.ld" \
		-Wl,-v \
		-o ${NAME}.elf \

build: link

clean:
	@rm -rf ${BUILD_DIR} ./*.o
