import unicodedata, html.entities
out=[]
out.append("// Generated by tools/gencharmap.py --- do not edit by hand.\n")
# 1. CP437 upper half: code point for each byte 0x80..0xFF, plus the glyphs in 0x01..0x1F
pairs={}
for b in range(0x80,0x100):
    pairs[ord(bytes([b]).decode('cp437'))]=b
# CP437 graphic glyphs at control positions (IBM PC font)
ctrl="☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼"
for i,ch in enumerate(ctrl):
    b=i+1
    if b in (0x0a,0x0d,0x09): continue   # keep these out: they are whitespace to the parser
    pairs.setdefault(ord(ch),b)
# This font is CP437 for letters and the Latin-1 symbols (0x80..0xAF), but
# its box-drawing and Greek/maths rows (0xB0..0xFF) and most of the control
# glyphs are different drawings.  Only the positions checked by eye against
# R2_TerminusFont.h are kept; the rest fall through to transliteration.
verified={0xE1,0xE6,0xF1,0xF6,0xF8,0xF9,0xFA,0xFB,0xFD, 0x07,0x09,0x14,0x15,0x18,0x19,0x1A,0x1B}
pairs={cp:b for cp,b in pairs.items() if (0x80<=b<0xB0) or b in verified}
# 2. transliteration for U+00A0..U+024F not in CP437: strip diacritics
extra={0x00A0:0x20,0x00AD:None,0x00D0:ord('D'),0x00F0:ord('d'),0x00D8:ord('O'),0x00F8:ord('o'),0x00DE:ord('T'),0x00FE:ord('t'),
       0x0110:ord('D'),0x0111:ord('d'),0x0141:ord('L'),0x0142:ord('l'),0x0131:ord('i'),0x0152:ord('O'),0x0153:ord('o'),
       0x00A9:ord('c'),0x00AE:ord('R'),0x00B4:0x27,0x00B8:ord(','),0x00A8:ord('"'),0x00AF:ord('-'),0x00B9:ord('1'),0x00B3:ord('3'),
       0x00BE:ord('?'),0x00A4:ord('*'),0x00A6:ord('|'),0x00D7:ord('x'),0x00B6:0x14}
# punctuation & symbols
punct={0x2010:'-',0x2011:'-',0x2012:'-',0x2013:'-',0x2014:'-',0x2015:'-',0x2018:"'",0x2019:"'",0x201A:',',0x201B:"'",
       0x201C:'"',0x201D:'"',0x201E:'"',0x201F:'"',0x2032:"'",0x2033:'"',0x2039:'<',0x203A:'>',0x2044:'/',0x2002:' ',0x2003:' ',
       0x2009:' ',0x200A:' ',0x2007:' ',0x2008:' ',0x202F:' ',0x205F:' ',0x2212:'-',0x2215:'/',0x2217:'*',0x2223:'|',0x2227:'^',
       0x2260:'#',0x2026:'.',0x20AC:'E',0x2122:'T',0x2713:'v',0x2714:'v',0x2717:'x',0x2718:'x',0x2605:'*',0x2606:'*',0x25CF:0x07,
       0x2023:0x07,0x2043:'-',0x25E6:0x09,0x2027:0xFA,0x21D2:0x1A,0x21D0:0x1B,0x2192:0x1A,0x2190:0x1B,0x2191:0x18,0x2193:0x19,
       0x2194:0x1D,0x00B7:0xFA,0x30FB:0xFA,0x2219:0xF9,0xFEFF:None,0x200B:None,0x200C:None,0x200D:None,0x200E:None,0x200F:None,0x2060:None}
table={}
for cp,b in pairs.items(): table[cp]=b
for cp in range(0xA0,0x250):
    if cp in table: continue
    if cp in extra:
        table[cp]=extra[cp]; continue
    d=unicodedata.normalize('NFD',chr(cp))
    base=d[0]
    if ord(base)<0x80 and base.isalpha():
        table[cp]=ord(base)
    elif ord(base) in pairs:
        table[cp]=pairs[ord(base)]
for cp,v in punct.items():
    if cp in table: continue
    table[cp]= (ord(v) if isinstance(v,str) else v)
# emit sorted pairs; 0 means "drop the character"
items=sorted(table.items())
out.append("static const uint16_t kUniMap[][2] = {\n")
for cp,b in items:
    out.append("    {0x%04X, 0x%02X},\n"%(cp, 0 if b is None else b))
out.append("};\n\n")
# 3. single-byte charsets 0x80..0xFF -> unicode
for name,codec in (("kCp1252","cp1252"),("kCp1250","cp1250"),("kIso88592","iso8859_2")):
    out.append("static const uint16_t %s[128] = {\n"%name)
    row=[]
    for b in range(0x80,0x100):
        try: cp=ord(bytes([b]).decode(codec))
        except UnicodeDecodeError: cp=0xFFFD
        row.append("0x%04X"%cp)
    for i in range(0,128,8): out.append("    "+", ".join(row[i:i+8])+",\n")
    out.append("};\n\n")
# 4. entities
names="""amp lt gt quot apos nbsp copy reg trade hellip mdash ndash lsquo rsquo ldquo rdquo sbquo bdquo laquo raquo bull middot
times divide deg plusmn para sect euro pound yen cent frac12 frac14 frac34 sup1 sup2 sup3 micro larr rarr uarr darr harr hearts
shy zwnj zwj thinsp ensp emsp prime Prime iexcl iquest acute cedil uml macr ordf ordm not brvbar curren minus lowast le ge ne
aacute eacute iacute oacute uacute yacute Aacute Eacute Iacute Oacute Uacute Yacute agrave egrave igrave ograve ugrave Agrave
Egrave Igrave Ograve Ugrave auml euml iuml ouml uuml yuml Auml Euml Iuml Ouml Uuml acirc ecirc icirc ocirc ucirc Acirc Ecirc
Icirc Ocirc Ucirc atilde otilde ntilde Atilde Otilde Ntilde ccedil Ccedil szlig aring Aring aelig AElig oslash Oslash eth ETH
thorn THORN scaron Scaron zcaron Zcaron ccaron Ccaron ecaron Ecaron rcaron Rcaron ncaron Ncaron dcaron Dcaron tcaron Tcaron
uring Uring lstrok Lstrok oelig OElig dagger Dagger permil lsaquo rsaquo infin asymp equiv sum prod radic alpha beta gamma
delta epsilon pi sigma tau phi omega Omega Sigma Phi Gamma Theta mu check cross star starf larrow rarrow""".split()
ents=[]
for n in names:
    key=n+';'
    if key in html.entities.html5:
        s=html.entities.html5[key]
        if len(s)==1: ents.append((n,ord(s)))
ents.sort()
out.append("struct Entity\n{\n    const char *name;\n    uint16_t cp;\n};\n\n")
out.append("static const Entity kEntities[] = {\n")
for n,cp in ents: out.append('    {"%s", 0x%04X},\n'%(n,cp))
out.append("};\n")
open("charmap.inc","w").write("".join(out))
print(len(items),"map entries,",len(ents),"entities")
