//go:build ignore

// gen.go writes font.go and charmap.go from Memento's own tables, so that
// telegram.elf draws with the glyphs Memento draws with and maps text the
// way its web engine does.
//
//	go run tools/gen.go [memento-src] [web-dir]
package main

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strconv"
)

func main() {
	memento, web := "../../../Memento/src", "../../cpp/memento-hello/web"
	if len(os.Args) > 2 {
		memento, web = os.Args[1], os.Args[2]
	}
	font := read(memento + "/ui/platform/impl/r2/R2_TerminusFont.h")
	charmap := read(web + "/charmap.inc")

	width := number(font, `r2_font_char_width\s*=\s*(\d+)`)
	height := number(font, `r2_font_char_height\s*=\s*(\d+)`)
	start := bytes.Index(font, []byte("r2_terminus_glyphs"))
	glyphs := regexp.MustCompile(`0x[0-9a-fA-F]{2}`).FindAll(font[start:], -1)
	if len(glyphs) != 256*height {
		fail("%d glyph bytes, want %d", len(glyphs), 256*height)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by tools/gen.go from Memento's R2_TerminusFont.h; DO NOT EDIT.\n\npackage main\n\n")
	fmt.Fprintf(&out, "const (\n\tglyphW = %d\n\tglyphH = %d\n)\n\n", width, height)
	out.WriteString("// glyphs is code page 437 in Terminus, glyphH rows a character, the\n// leftmost pixel in the top bit.\nvar glyphs = [256 * glyphH]byte{")
	for i, g := range glyphs {
		if i%height == 0 {
			out.WriteString("\n\t")
		} else {
			out.WriteString(" ")
		}
		out.Write(g)
		out.WriteString(",")
	}
	out.WriteString("\n}\n")
	write("font.go", out.Bytes())

	pairs := regexp.MustCompile(`\{\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*\}`).FindAllSubmatch(charmap, -1)
	if len(pairs) < 100 {
		fail("only %d charmap entries", len(pairs))
	}
	out.Reset()
	out.WriteString("// Code generated by tools/gen.go from Memento's web/charmap.inc; DO NOT EDIT.\n\npackage main\n\n")
	out.WriteString("// uniMap is the glyph for each code point past ASCII the font can show,\n// sorted by code point.\nvar uniMap = [...][2]uint16{")
	for i, p := range pairs {
		if i%6 == 0 {
			out.WriteString("\n\t")
		} else {
			out.WriteString(" ")
		}
		fmt.Fprintf(&out, "{%s, %s},", p[1], p[2])
	}
	out.WriteString("\n}\n")
	write("charmap.go", out.Bytes())
}

func read(path string) []byte {
	b, err := os.ReadFile(path)
	if err != nil {
		fail("%v", err)
	}
	return b
}

func write(path string, b []byte) {
	if err := os.WriteFile(path, b, 0o644); err != nil {
		fail("%v", err)
	}
}

func number(b []byte, re string) int {
	m := regexp.MustCompile(re).FindSubmatch(b)
	if m == nil {
		fail("%s not found", re)
	}
	n, _ := strconv.Atoi(string(m[1]))
	return n
}

func fail(format string, v ...any) {
	fmt.Fprintf(os.Stderr, "gen: "+format+"\n", v...)
	os.Exit(1)
}
